version: '3.3'

services:
  login-backend:
    image: gsamrit/career-forge-login:latest
    container_name: login-backend
    environment:
      - NODE_ENV=production
      - PORT=3009
    ports:
      - "3009:3009"
    networks:
      - app-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5044"

  login-frontend:
    image: gsamrit/career-forge-frontend:latest
    container_name: login-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://login-backend:3009
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5044"
  
  company-service:
    image: gsamrit/career-forge-companyservice:latest
    container_name: company-service
    environment:
      - REACT_APP_BACKEND_URL=http://login-backend:3009
      - NODE_ENV=production
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - app-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5044"
  
  admin-service:
    image: gsamrit/career-forge-adminservice:latest
    container_name: admin-service
    ports:
      - "3001:3001"
    networks:
      - app-network
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5044"

networks:
  app-network:
    driver: bridge
